version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  springboot-app:
    image: test-app
    container_name: test-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9100:9100"
    environment:
      MYSQL_HOST: mysql-container
      MYSQL_PORT: 3306
    depends_on:
      - mysql

